fos_user:
    db_driver:		orm # otros valores válidos son 'mongodb', 'couchdb
    firewall_name:	login
    user_class:		AppBundle\Entity\User
#     user_class:		Application\Sonata\UserBundle\Entity\User

#     group:
#         group_class:	Application\Sonata\UserBundle\Entity\Group
#         group_manager:	sonata.user.orm.group_manager

#     service:
#         user_manager:	sonata.user.orm.user_manager

#     profile:
#         # Authentication Form
#         form:
#             type:				fos_user_profile
#             handler:			fos_user.profile.form.handler.default
#             name:				fos_user_profile_form
#             validation_groups:	[Authentication]
