<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * CasosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasosRepository extends EntityRepository
{
	public function findAllPaginated(array $filters = array(), array $order_by = array(), $limit, $offset)
	{
        /*$persister = $this->_em->getUnitOfWork()->getEntityPersister($this->_entityName);
        return $persister->loadAll($criteria, $orderBy, $limit, $offset);*/

		$fields = array_keys($this->getClassMetadata()->reflFields);
        $queryBuilder = $this->createQueryBuilder('c');

        foreach ($fields as $field) {
            if (isset($order_by[$field])) {
                $direction = ($order_by[$field] === 'asc') ? 'asc' : 'desc';
                $queryBuilder->addOrderBy('c.'.$field, $direction);
            }
            if (isset($filters[$field])) {
                $queryBuilder->where('c.' . $field . '=' . $filters[$field]);
            }
        }

        $pagerAdapter = new DoctrineORMAdapter($queryBuilder);
        $pager = new Pagerfanta($pagerAdapter);
        $pager->setCurrentPage($offset);
        $pager->setMaxPerPage($limit);

        return $pager;
	}
}
